<a href="https://colab.research.google.com/github/Sumanthbabu-Muthineni/collab-tensorflow/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#learning tensor flow fundamentals
More specifically i'm going to learn:
* introduction to tensors
* getting information from tensors
* manipulating tensors
* tensors & numpy
* using @tf.function( a way to speed up regular python functions)
* Using gpus with tensorflow or TPUS
* Exercises




# Introduction to tensors

In [4]:
#import tensor flow
import tensorflow as tf
print(tf.__version__)



2.18.0


In [5]:
#creating tensors with tf.constant()
scalar=tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [6]:
#check no. of dimensions of a tensor (ndim stands for no. of dimensions)
scalar.ndim

0

In [7]:
#Create a vector
vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [8]:
#check dimension of vector
vector.ndim


1

In [9]:
#create a matrix (has more than one dimension)
matrix=tf.constant([[10,7],[7,10]])
matrix


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [10]:
matrix.ndim

2

In [11]:
#Create another matrix
another_matrix=tf.constant([[10.,7.],[3.,2.],[8.,9.]],dtype=tf.float16) #specify the data type with dtype param. so here bydefault its taking int32 as dtype
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [12]:
#whats the no. of dimensions of another_matrix?
another_matrix.ndim

2

In [13]:
#lets create a tensor
tensor=tf.constant([     [[1,2,3],[4,5,6]]  , [[7,8,9],[10,11,12]], [[13,14,15],[16,17,18]]                  ])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [14]:
tensor.ndim

3

what we've created so far:

* Scalar: a single number
* Vector: a number with direction (e.g. wind speed and direction)
* Matrix: a 2-dimensional array of numbers
* Tensor: a n-dimensional array of numbers (where n can be any number ,for ex: a 0-dimensional tensor is a scalar ,a 1-dimensional tensor is a vector)


### Creating Tensors with `tf.Variable`

In [15]:
#Create the same tensor with tf.Variable() as above
changeable_tensor=tf.Variable([10,7])
unchangeable_tensor=tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [16]:
#lets try change one of the elements in our changeable tensor
changeable_tensor[0]=7
changeable_tensor

TypeError: 'ResourceVariable' object does not support item assignment

In [ ]:
# how about we try .assign()
changeable_tensor[0].assign(7)
changeable_tensor



In [ ]:
#lets try change in unchangeable tensor
unchangeable_tensor[0].assign(7)

### Creating random tensors

Random tensors are tensors of some arbitrary size which contain random number




In [ ]:
#Create  two random (but the same ) tensors
random_1=tf.random.Generator.from_seed(42) #set seed for reproducibility
random_1=random_1.normal(shape=(3,2))
random_2=tf.random.Generator.from_seed(42)
random_2=random_2.normal(shape=(3,2))
#Are they equal
random_1, random_2, random_1==random_2

### Shuffle the order of elements in a tensor

In [ ]:
#shuffle a tensor (valuable when you want to shuffle your data so that inherent data order doesn't effect learning)
import tensorflow as tf
not_shuffled = tf.constant([[10,7],[3,4],[2,5]])

#shuffle our non-shuffled tensor
tf.random.shuffle(not_shuffled,seed=42)



In [ ]:
#shuffle our non-shuffled tensor with both global and operation seed ,we get same order every time. so here global and operation seed together shuffle and give same random sequence everytime.
tf.random.set_seed(42) #global level seed
tf.random.shuffle(not_shuffled,seed=42) #operation level seed


In [ ]:
not_shuffled

### Otherways to make Tensors

In [ ]:
#Create a tensor of all ones
tf.ones([10,7])

In [ ]:
# Create a tensor of all zeroes ... shape can be passed as square brackets or curly brackets.. like this [10,10 ] or shape=(10,10)
tf.zeros([10,10])

### Turn numpy arrays into tensors
The main difference between Numpy arrays and tensorFlow tensors is that tensors can be run on a  GPU (much faster for numerical computing)

In [ ]:
#You can also turn numpys into tensors
import numpy as np
numpy_A = np.arange(1,25,dtype=np.int32) #Create a numpy array between 1 and 25
numpy_A
#X=tf.constant(some_matrix) #capital for matrix or tensor
#y=tf.constant(vector) #non capital for vector


In [ ]:
A=tf.constant(numpy_A,shape=(2,2,6)) #tensor  (shape numbers product should equal to no. of elements in numpy array here it is 24)
B=tf.constant(numpy_A) #vector
A,B

In [ ]:
A.ndim

### Get Information from tensors
When dealing with tensors you probably want to be aware of the following attirbutes:
* Shape
* Rank
* Axis or Dimension
* Size



In [ ]:
#Create a rank 4 tensor (4 dimensions )
rank_4_tensor=tf.zeros(shape=[2,3,4,5])
rank_4_tensor

In [ ]:
rank_4_tensor.shape ,rank_4_tensor.ndim, tf.size(rank_4_tensor)

In [ ]:
2*3*4*5

In [ ]:
#Get Various attributes of our tensor
print("Datatype of every element:",rank_4_tensor.dtype)
print("No. of dimensions:", rank_4_tensor.ndim)
print("Shape of the tensor", rank_4_tensor.shape)
print("Elements along the 0 axis", rank_4_tensor.shape[0])
print("Elements along the last axis" ,rank_4_tensor.shape[-1])
print("Total no. of elements in tensors" ,tf.size(rank_4_tensor))
print("Total no. of elements in tensors" ,tf.size(rank_4_tensor).numpy())


### Indexing tensors
Tensors can be indexed just like python lists


In [ ]:
some_list=[1,2,3,4]
some_list[:2]


In [ ]:
rank_4_tensor.shape

In [ ]:
#Get the first 2 elements of each dimension
rank_4_tensor[:2,:2,:2,:2]

In [ ]:
some_list[:1]


In [ ]:
#Get first element from each dimension from each index execpt for the final one
rank_4_tensor[:1,:1,:1,:]


In [ ]:
rank_4_tensor[:1,:1,:,:1]

In [ ]:
rank_4_tensor[:1,:,:1,:1]

In [ ]:
rank_4_tensor[:,:1,:1,:1]

In [ ]:
#Create a rank 2 tensor ( 2 dimensions)
rank_2_tensor=tf.constant([[10,7],[3,4]])
rank_2_tensor.shape,rank_2_tensor.ndim
rank_2_tensor

In [ ]:
#Get the last item of each row of our rank 2 tensor
rank_2_tensor[:,-1]

In [ ]:
#Add  in extra dimension to our rank 2 tensor
rank_3_tensor=rank_2_tensor[...,tf.newaxis]
rank_3_tensor

In [ ]:
#alternative to tf.newaxis is
tf.expand_dims(rank_2_tensor,axis=-1) #"-1" means expand  the final axis


In [ ]:
#Expand the 0 axis
tf.expand_dims(rank_2_tensor,axis=0) #expand the 0-axis

In [ ]:
rank_2_tensor

### Manipulating tensors (tensors operations)

** Basic operations **

`+`,`-`,`*`,`/`




In [18]:
#you can add values to a tensor using addition param
tensor=tf.constant([[10,7],[3,4]])
tensor+10


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [19]:
# Original tensor is unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
#Multiplication also works
tensor * 10

In [ ]:
#Substraction
tensor - 10

In [21]:
#We can use the tensor flow built in function too
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [22]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

###Matrix Multiplication
In machine learning, matrix Multiplication is one of the most common tensor operations

There are two rules our tensors (or matrices need to fullfill  if we're going to matrix multiply them:
* The inner dimensions must match
* The  resulting matrix has the shape of the outter dimensions

In [24]:
#Matrix Multiplcation in tensor flow
print(tensor)
tf.matmul(tensor,tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [26]:
#matrix multplication with python operator "@"
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [27]:
tensor.shape

TensorShape([2, 2])

In [34]:
#Create a tensor (3,2) tensor
X= tf.constant([[1,2],[3,4],[5,6]])
Y=tf.constant([[7,8],[9,10],[11,12]])
X,Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [36]:
#Try to matrix multiply tensors of same shape
tf.matmul(X,Y)

InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul] name: 

In [37]:
#Lets change the shape of Y
tf.reshape(Y,shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [41]:
X.shape,tf.reshape(Y,shape=(2,3)).shape

(TensorShape([3, 2]), TensorShape([2, 3]))

In [40]:
#Try to multiply X by reshaped Y
tf.matmul(X,tf.reshape(Y,shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [43]:
#Can do the same with transpose
X,tf.transpose (X),tf.reshape(X,shape=(2,3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

In [44]:
 #Try matrix multiplication with transpose rather than reshape
tf.matmul(tf.transpose(X),Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

**The Dot Product**

Matric Multiplication is also referred  to as a dot product
you cna perform matrix multiplication using:
* `tf.matmul()`
* `tf.tensordot()`
* `@`

In [47]:
#Perform dot product on X and Y (requires X or y to be transposed)
tf.tensordot(tf.transpose(X),Y,axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [50]:
#perform matrix multiplication between X and Y (transposed)

tf.tensordot(X,tf.transpose(Y),axes=1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [51]:
#perform matrix multiplication between X and Y (reshaped)
tf.matmul(X,tf.reshape(Y,shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [52]:
#Check the values of Y ,reshape Y and transpose Y
print("Normal Y:" )
print(Y,"\n")
print("Y reshaped to (2,3):")
print(tf.reshape(Y,(2,3)),"\n")
print("Y transposed: " )
print(tf.transpose(Y))

Normal Y:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y reshaped to (2,3):
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Y transposed: 
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


In [53]:
tf.matmul(X,tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

Generally while performing matrix multiplication between two sensors and if one of the axes doesn't lineup. you will transpose one of the matrix (instead of reshape) to get satisy the multiplication

### Changing the datatype of a tensor

In [ ]:
#Create a new tensor with default datatype (float32)
