<a href="https://colab.research.google.com/github/Sumanthbabu-Muthineni/collab-tensorflow/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#learning tensor flow fundamentals
More specifically i'm going to learn:
* introduction to tensors
* getting information from tensors
* manipulating tensors
* tensors & numpy
* using @tf.function( a way to speed up regular python functions)
* Using gpus with tensorflow or TPUS
* Exercises




# Introduction to tensors

In [12]:
#import tensor flow
import tensorflow as tf
print(tf.__version__)



2.18.0


In [13]:
#creating tensors with tf.constant()
scalar=tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [14]:
#check no. of dimensions of a tensor (ndim stands for no. of dimensions)
scalar.ndim

0

In [15]:
#Create a vector
vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [16]:
#check dimension of vector
vector.ndim


1

In [17]:
#create a matrix (has more than one dimension)
matrix=tf.constant([[10,7],[7,10]])
matrix


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [18]:
matrix.ndim

2

In [19]:
#Create another matrix
another_matrix=tf.chttps://www.udemy.com/course/tensorflow-developer-certificate-machine-learning-zero-to-mastery/learn/lecture/24843402#overviewonstant([[10.,7.],[3.,2.],[8.,9.]],dtype=tf.float16) #specify the data type with dtype param. so here bydefault its taking int32 as dtype
another_matrix

SyntaxError: invalid syntax (ipython-input-19-3536693435.py, line 2)

In [ ]:
#whats the no. of dimensions of another_matrix?
another_matrix.ndim

In [ ]:
#lets create a tensor
tensor=tf.constant([     [[1,2,3],[4,5,6]]  , [[7,8,9],[10,11,12]], [[13,14,15],[16,17,18]]                  ])
tensor

In [ ]:
tensor.ndim

what we've created so far:

* Scalar: a single number
* Vector: a number with direction (e.g. wind speed and direction)
* Matrix: a 2-dimensional array of numbers
* Tensor: a n-dimensional array of numbers (where n can be any number ,for ex: a 0-dimensional tensor is a scalar ,a 1-dimensional tensor is a vector)


### Creating Tensors with `tf.Variable`

In [ ]:
#Create the same tensor with tf.Variable() as above
changeable_tensor=tf.Variable([10,7])
unchangeable_tensor=tf.constant([10,7])
changeable_tensor, unchangeable_tensor

In [ ]:
#lets try change one of the elements in our changeable tensor
changeable_tensor[0]=7
changeable_tensor

In [ ]:
# how about we try .assign()
changeable_tensor[0].assign(7)
changeable_tensor



In [ ]:
#lets try change in unchangeable tensor
unchangeable_tensor[0].assign(7)

### Creating random tensors

Random tensors are tensors of some arbitrary size which contain random number




In [ ]:
#Create  two random (but the same ) tensors
random_1=tf.random.Generator.from_seed(42) #set seed for reproducibility
random_1=random_1.normal(shape=(3,2))
random_2=tf.random.Generator.from_seed(42)
random_2=random_2.normal(shape=(3,2))
#Are they equal
random_1, random_2, random_1==random_2

### Shuffle the order of elements in a tensor

In [ ]:
#shuffle a tensor (valuable when you want to shuffle your data so that inherent data order doesn't effect learning)
import tensorflow as tf
not_shuffled = tf.constant([[10,7],[3,4],[2,5]])

#shuffle our non-shuffled tensor
tf.random.shuffle(not_shuffled,seed=42)



In [ ]:
#shuffle our non-shuffled tensor with both global and operation seed ,we get same order every time. so here global and operation seed together shuffle and give same random sequence everytime.
tf.random.set_seed(42) #global level seed
tf.random.shuffle(not_shuffled,seed=42) #operation level seed


In [ ]:
not_shuffled

### Otherways to make Tensors

In [ ]:
#Create a tensor of all ones
tf.ones([10,7])

In [ ]:
# Create a tensor of all zeroes ... shape can be passed as square brackets or curly brackets.. like this [10,10 ] or shape=(10,10)
tf.zeros([10,10])

### Turn numpy arrays into tensors
The main difference between Numpy arrays and tensorFlow tensors is that tensors can be run on a  GPU (much faster for numerical computing)

In [ ]:
#You can also turn numpys into tensors
import numpy as np
numpy_A = np.arange(1,25,dtype=np.int32) #Create a numpy array between 1 and 25
numpy_A
#X=tf.constant(some_matrix) #capital for matrix or tensor
#y=tf.constant(vector) #non capital for vector


In [ ]:
A=tf.constant(numpy_A,shape=(2,2,6)) #tensor  (shape numbers product should equal to no. of elements in numpy array here it is 24)
B=tf.constant(numpy_A) #vector
A,B

In [ ]:
A.ndim

### Get Information from tensors
When dealing with tensors you probably want to be aware of the following attirbutes:
* Shape
* Rank
* Axis or Dimension
* Size



In [ ]:
#Create a rank 4 tensor (4 dimensions )
rank_4_tensor=tf.zeros(shape=[2,3,4,5])
rank_4_tensor

In [ ]:
rank_4_tensor.shape ,rank_4_tensor.ndim, tf.size(rank_4_tensor)

In [20]:
2*3*4*5

120

In [21]:
#Get Various attributes of our tensor
print("Datatype of every element:",rank_4_tensor.dtype)
print("No. of dimensions:", rank_4_tensor.ndim)
print("Shape of the tensor", rank_4_tensor.shape)
print("Elements along the 0 axis", rank_4_tensor.shape[0])
print("Elements along the last axis" ,rank_4_tensor.shape[-1])
print("Total no. of elements in tensors" ,tf.size(rank_4_tensor))
print("Total no. of elements in tensors" ,tf.size(rank_4_tensor).numpy())


NameError: name 'rank_4_tensor' is not defined

### Indexing tensors
Tensors can be indexed just like python lists


In [22]:
some_list=[1,2,3,4]
some_list[:2]


[1, 2]

In [23]:
rank_4_tensor.shape

NameError: name 'rank_4_tensor' is not defined

In [24]:
#Get the first 2 elements of each dimension
rank_4_tensor[:2,:2,:2,:2]

NameError: name 'rank_4_tensor' is not defined

In [25]:
some_list[:1]


[1]

In [26]:
#Get first element from each dimension from each index execpt for the final one
rank_4_tensor[:1,:1,:1,:]


NameError: name 'rank_4_tensor' is not defined

In [27]:
rank_4_tensor[:1,:1,:,:1]

NameError: name 'rank_4_tensor' is not defined

In [28]:
rank_4_tensor[:1,:,:1,:1]

NameError: name 'rank_4_tensor' is not defined

In [29]:
rank_4_tensor[:,:1,:1,:1]

NameError: name 'rank_4_tensor' is not defined

In [30]:
#Create a rank 2 tensor ( 2 dimensions)
rank_2_tensor=tf.constant([[10,7],[3,4]])
rank_2_tensor.shape,rank_2_tensor.ndim
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [31]:
#Get the last item of each row of our rank 2 tensor
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [32]:
#Add  in extra dimension to our rank 2 tensor
rank_3_tensor=rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [33]:
#alternative to tf.newaxis is
tf.expand_dims(rank_2_tensor,axis=-1) #"-1" means expand  the final axis


<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [34]:
#Expand the 0 axis
tf.expand_dims(rank_2_tensor,axis=0) #expand the 0-axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

In [35]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

### Manipulating tensors (tensors operations)

** Basic operations **

`+`,`-`,`*`,`/`




In [36]:
#you can add values to a tensor using addition param
tensor=tf.constant([[10,7],[3,4]])
tensor+10


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [37]:
# Original tensor is unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [38]:
#Multiplication also works
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [39]:
#Substraction
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [40]:
#We can use the tensor flow built in function too
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [41]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

###Matrix Multiplication
In machine learning, matrix Multiplication is one of the most common tensor operations

There are two rules our tensors (or matrices need to fullfill  if we're going to matrix multiply them:
* The inner dimensions must match
* The  resulting matrix has the shape of the outter dimensions

In [42]:
#Matrix Multiplcation in tensor flow
print(tensor)
tf.matmul(tensor,tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [43]:
#matrix multplication with python operator "@"
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [44]:
tensor.shape

TensorShape([2, 2])

In [45]:
#Create a tensor (3,2) tensor
X= tf.constant([[1,2],[3,4],[5,6]])
Y=tf.constant([[7,8],[9,10],[11,12]])
X,Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [46]:
#Try to matrix multiply tensors of same shape
tf.matmul(X,Y)

InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul] name: 

In [47]:
#Lets change the shape of Y
tf.reshape(Y,shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [48]:
X.shape,tf.reshape(Y,shape=(2,3)).shape

(TensorShape([3, 2]), TensorShape([2, 3]))

In [49]:
#Try to multiply X by reshaped Y
tf.matmul(X,tf.reshape(Y,shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [50]:
#Can do the same with transpose
X,tf.transpose (X),tf.reshape(X,shape=(2,3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

In [51]:
 #Try matrix multiplication with transpose rather than reshape
tf.matmul(tf.transpose(X),Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

**The Dot Product**

Matric Multiplication is also referred  to as a dot product
you cna perform matrix multiplication using:
* `tf.matmul()`
* `tf.tensordot()`
* `@`

In [52]:
#Perform dot product on X and Y (requires X or y to be transposed)
tf.tensordot(tf.transpose(X),Y,axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [53]:
#perform matrix multiplication between X and Y (transposed)

tf.tensordot(X,tf.transpose(Y),axes=1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [54]:
#perform matrix multiplication between X and Y (reshaped)
tf.matmul(X,tf.reshape(Y,shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [55]:
#Check the values of Y ,reshape Y and transpose Y
print("Normal Y:" )
print(Y,"\n")
print("Y reshaped to (2,3):")
print(tf.reshape(Y,(2,3)),"\n")
print("Y transposed: " )
print(tf.transpose(Y))

Normal Y:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y reshaped to (2,3):
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Y transposed: 
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


In [56]:
tf.matmul(X,tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

Generally while performing matrix multiplication between two sensors and if one of the axes doesn't lineup. you will transpose one of the matrix (instead of reshape) to get satisy the multiplication

### Changing the datatype of a tensor

In [57]:
#Create a new tensor with default datatype (float32)
B=tf.constant([7,10])
c=tf.constant([7.3,4.5])
B.dtype,c.dtype

(tf.int32, tf.float32)

In [58]:
tf.__version__

'2.18.0'

In [59]:
#Change from float32 to float16 (reduced precision)
B=tf.cast(B,dtype=tf.float16)
B

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([ 7., 10.], dtype=float16)>

In [60]:
C=tf.constant([7,10])
C.dtype

tf.int32

In [61]:
E=tf.cast(C,dtype=tf.float32)
E

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 7., 10.], dtype=float32)>

### Aggregating tensors


> Aggregating tensors =condensing them from multiple values down to a smaller amount of values







In [62]:
# Get the absolete values
D=tf.constant([-7,-10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [63]:
 #Get the absolete values
tf.abs(D)


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Lets go through following forms of aggregation

* Get the minimum
* Get the maximum
*  Get the mean of a tensor
* Get the sum of a tensor


In [64]:
#Createa random tensor with values between 0 and 100 of size 50
E=tf.constant(np.random.randint(0,100,size=50))
E

NameError: name 'np' is not defined

In [65]:

tf.size(E),E.shape ,E.ndim


(<tf.Tensor: shape=(), dtype=int32, numpy=2>, TensorShape([2]), 1)

In [66]:
#find the minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=float32, numpy=7.0>

In [67]:
#find the maximum
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=float32, numpy=10.0>

In [68]:
#Find the mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=float32, numpy=8.5>

In [69]:
#Find the sum
tf.reduce_sum(E)


<tf.Tensor: shape=(), dtype=float32, numpy=17.0>

In [70]:
#Find the  variance of our tensor
import tensorflow_probability as tfp
tfp.stats.variance(E)


<tf.Tensor: shape=(), dtype=float32, numpy=2.25>

In [71]:
#find the standard deviation dtype should be float32 while using reduce_std.Else we might get error like E should be either real or complex
tf.math.reduce_std(tf.cast(E,dtype=tf.float32))


<tf.Tensor: shape=(), dtype=float32, numpy=1.5>

In [72]:
#find the variance, dtype should be float32 while using reduce_variance. Else we might get error like E should be either real or complex ..this method help us rid off tfp.stats.variance
tf.math.reduce_variance(tf.cast(E,dtype=tf.float32))



<tf.Tensor: shape=(), dtype=float32, numpy=2.25>

###Find the position maximum and minimum

In [73]:
# Create  a new tensor for finding positional maximum and minimum
tf.random.set_seed(42)
F=tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [74]:
#Find the positional maximum
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [75]:
#index on our largest value position
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.967138409614563>

In [76]:
#Find the max value of F
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.967138409614563>

In [77]:
#check for equality
F[tf.argmax(F)]== tf.reduce_max(F)


<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [78]:
#Find the positional minimum
tf.argmin(F)


<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [79]:
 #Find the minimum  using the positional minimum index
F[tf.argmin(F)]


<tf.Tensor: shape=(), dtype=float32, numpy=0.009463667869567871>

In [80]:
F[tf.argmin(F)]==tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

### Squeezing  a tensor (Removing all single dimensions)



In [81]:
#Create a tensor  to get started
tf.random.set_seed(42)
G=tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [82]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [83]:
G_squeezed=tf.squeeze(G)
G_squeezed,G_squeezed.shape


(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))

### one-hot encoding tensor

In [84]:
#Create a list of indices
some_list=[0,1,2,3] #could be blue green red yellow
#one hot encoding  our list of indices
tf.one_hot(some_list,depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [85]:
#specify custom values  for one hot encoding
tf.one_hot(some_list,depth=4,on_value="hey man",off_value="yes bro")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'hey man', b'yes bro', b'yes bro', b'yes bro'],
       [b'yes bro', b'hey man', b'yes bro', b'yes bro'],
       [b'yes bro', b'yes bro', b'hey man', b'yes bro'],
       [b'yes bro', b'yes bro', b'yes bro', b'hey man']], dtype=object)>

In [86]:
tf.one_hot(some_list,depth=4,on_value=0.5,off_value=0.2)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0.5, 0.2, 0.2, 0.2],
       [0.2, 0.5, 0.2, 0.2],
       [0.2, 0.2, 0.5, 0.2],
       [0.2, 0.2, 0.2, 0.5]], dtype=float32)>

### Squaring   ,log, square root

In [87]:
H=tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [88]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [89]:
tf.sqrt(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [91]:
tf.math.log(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Tensors and Numpy
Tensorflow interacts beautifully with numpy arrays .

In [97]:
#Create a tensor directly from a numpy array
import numpy as np
J=tf.constant(np.array([3,7,0.5,0.9]))
J

<tf.Tensor: shape=(4,), dtype=float64, numpy=array([3. , 7. , 0.5, 0.9])>

In [98]:
#Convert back tensors back to a nmupy array
np.array(J),type(np.array(J))

(array([3. , 7. , 0.5, 0.9]), numpy.ndarray)

In [99]:
#convert tensor J to a numpy array
J.numpy(),type(J.numpy())

(array([3. , 7. , 0.5, 0.9]), numpy.ndarray)

In [100]:
#the default types of each are slightly different
numpy_J= tf.constant(np.array([3.,7.,10.]))
tensor_j=tf.constant([3.,7.,10.])
#check the datatypes of each
numpy_J.dtype,tensor_j.dtype


(tf.float64, tf.float32)